import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { allProducts, comparisons } from "../client/src/lib/products";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(__dirname, "site-data.json");
const reportPath = resolve(__dirname, "..", "price-sync-report.json");
const freshnessModulePath = resolve(__dirname, "..", "client", "src", "lib", "priceFreshness.generated.ts");
const MAX_PRICE_AGE_MS = 24 * 60 * 60 * 1000;

function priceFreshnessByAsin(products: typeof allProducts) {
  const fallback = Object.fromEntries(products.map((product) => [product.asin, false]));
  if (!existsSync(reportPath)) return { generatedAt: "", freshness: fallback };
  try {
    const report = JSON.parse(readFileSync(reportPath, "utf8"));
    const generatedAt = typeof report.generatedAt === "string" ? report.generatedAt : "";
    const generatedAtMs = Date.parse(generatedAt);
    const current = report.mode === "live" && Number.isFinite(generatedAtMs) && Date.now() - generatedAtMs >= 0 && Date.now() - generatedAtMs < MAX_PRICE_AGE_MS;
    const updated = new Set(Array.isArray(report.updated) ? report.updated : []);
    const flagged = new Set(Array.isArray(report.flagged) ? report.flagged.map((item: { asin?: string }) => item.asin) : []);
    return {
      generatedAt,
      freshness: Object.fromEntries(products.map((product) => [product.asin, Boolean(current && updated.has(product.asin) && !flagged.has(product.asin))])),
    };
  } catch {
    return { generatedAt: "", freshness: fallback };
  }
}

function writeFreshnessModule(generatedAt: string, freshness: Record<string, boolean>) {
  const source = [
    "// Generated by scripts/extract-site-data.ts. Defaults are intentionally fail-closed.",
    `export const priceSyncGeneratedAt = ${JSON.stringify(generatedAt)};`,
    `export const priceFreshAsins: ReadonlySet<string> = new Set(${JSON.stringify(Object.keys(freshness).filter((asin) => freshness[asin]), null, 2)});`,
    "export const imageFreshAsins: ReadonlySet<string> = priceFreshAsins;",
    "",
    "export function isProductPriceFresh(asin?: string): boolean {",
    "  return Boolean(asin && priceFreshAsins.has(asin));",
    "}",
    "",
    "export function isProductImageFresh(asin?: string): boolean {",
    "  return Boolean(asin && imageFreshAsins.has(asin));",
    "}",
    "",
  ].join("\n");
  writeFileSync(freshnessModulePath, source, "utf8");
}

const productsById = new Map(allProducts.map((product) => [product.id, product]));
const productsBySlug = new Map<string, typeof allProducts[number]>();
for (const product of allProducts) {
  if (productsBySlug.has(product.slug)) {
    throw new Error(`Duplicate review slug in catalog: ${product.slug}`);
  }
  productsBySlug.set(product.slug, product);
}

const resolvableComparisons = comparisons.filter((comparison) => {
  const productIds = [comparison.product1Id, comparison.product2Id];
  const winnerId = comparison.winnerId;
  return productIds.every((id) => productsById.has(id)) && productsById.has(winnerId);
});

if (resolvableComparisons.length !== comparisons.length) {
  const invalid = comparisons
    .filter((comparison) => !resolvableComparisons.includes(comparison))
    .map((comparison) => comparison.slug)
    .join(", ");
  throw new Error(`Unresolvable comparison data: ${invalid}`);
}

const { generatedAt, freshness } = priceFreshnessByAsin(allProducts);
const productsWithFreshness = allProducts.map((product) => ({
  ...product,
  priceFresh: Boolean(freshness[product.asin]),
  imageFresh: Boolean(freshness[product.asin]),
}));
const payload = {
  allProducts: productsWithFreshness,
  comparisons: resolvableComparisons,
};
mkdirSync(dirname(outputPath), { recursive: true });
writeFreshnessModule(generatedAt, freshness);
writeFileSync(outputPath, JSON.stringify(payload, null, 2) + "\n");
console.log(`Validated ${allProducts.length} products and ${resolvableComparisons.length} comparisons -> ${outputPath}`);
