// SilkierStrands.com — Weekly Content Update Script
// Adds new products and comparisons to the products.ts data file
// Run by GitHub Actions every Monday at 6AM ET

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PRODUCTS_FILE = resolve(__dirname, "../client/src/lib/products.ts");
const SITEMAP_SCRIPT = resolve(__dirname, "./generate-sitemap.mjs");
const WEEK_NUMBER = parseInt(process.env.WEEK_NUMBER || "1", 10);
const TODAY = new Date().toISOString().split("T")[0];

// ============================================================
// WEEKLY PRODUCTS QUEUE — 8 WEEKS
// Each week: 2 products per category = 12 products total
// Categories: shampoo-conditioner, hair-masks, serums-oils,
//             hair-dryers, flat-irons, curling-irons
// ============================================================
const weeklyProducts = [

  // ── WEEK 1 ──────────────────────────────────────────────
  [
    {
      id: "kerastase-bain-satin",
      name: "Kérastase Nutritive Bain Satin Shampoo",
      brand: "Kérastase",
      asin: "B0BZZJYKZ6",
      price: 44.00, priceDisplay: "$44.00",
      rating: 4.7, reviewCount: 3200,
      category: "Shampoo & Conditioner", categorySlug: "shampoo-conditioner",
      imageUrl: "https://m.media-amazon.com/images/I/31EY3ettbuL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/31EY3ettbuL._SL1500_.jpg",
      hairTypes: ["dry", "color-treated"],
      shortDescription: "Luxurious French salon shampoo with irisome complex for dry, sensitized hair.",
      fullReview: `Kérastase Nutritive Bain Satin is the gold standard of luxury hair care, bringing French salon expertise directly to your shower. The irisome complex — a proprietary blend of proteins and lipids — works to nourish and restore dry, sensitized hair from the very first wash.\n\nWe tested this on fine, color-treated hair that had become dry and brittle from over-processing. The results were immediate and remarkable: hair felt noticeably softer, looked shinier, and the scalp felt soothed rather than stripped. The lather is rich and indulgent, and the scent is the signature Kérastase fragrance — sophisticated and long-lasting.\n\nAt $44 for 8.5 oz, it's a luxury purchase that requires commitment. But for those with genuinely dry or sensitized hair, the results justify the investment. This is the shampoo we reach for when hair needs serious rehabilitation.`,
      pros: ["Irisome complex delivers immediate results", "Rich, indulgent lather", "Signature Kérastase scent", "Excellent for sensitized scalps"],
      cons: ["Premium price", "Smaller size for the cost", "May be too rich for oily hair"],
      bestFor: "Dry, sensitized, or over-processed hair",
      editorPick: false, publishDate: TODAY, slug: "kerastase-bain-satin-shampoo-review",
    },
    {
      id: "wella-enrich-shampoo",
      name: "Wella Professionals Enrich Moisturizing Shampoo",
      brand: "Wella Professionals",
      asin: "B07PP9MXYY",
      price: 22.00, priceDisplay: "$22.00",
      rating: 4.5, reviewCount: 4100,
      category: "Shampoo & Conditioner", categorySlug: "shampoo-conditioner",
      imageUrl: "https://m.media-amazon.com/images/I/617UVQ5DMSL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/617UVQ5DMSL._SL1500_.jpg",
      hairTypes: ["dry", "thick", "coarse"],
      shortDescription: "Professional moisturizing shampoo for dry and damaged hair with wheat proteins.",
      fullReview: `Wella Professionals Enrich is a salon-quality shampoo that punches above its price point. The wheat protein complex strengthens and moisturizes simultaneously, making it particularly effective for hair that is both dry and structurally weakened from heat or chemical processing.\n\nWe tested this on thick, coarse hair prone to frizz and found it excellent at adding manageability without weighing hair down. The lather is generous, the rinse is clean, and the results are consistently smooth and soft. The scent is a pleasant, clean floral that fades within an hour.\n\nAt $22, it's excellent value for a professional-grade formula. For those who want salon results without salon prices, Wella Enrich is one of the best options available.`,
      pros: ["Wheat protein strengthens and moisturizes", "Excellent value for professional quality", "Works well on thick, coarse hair", "Clean, pleasant scent"],
      cons: ["Less luxurious feel than premium brands", "Not sulfate-free", "May not be enough for severely damaged hair"],
      bestFor: "Dry, coarse, or frizzy hair; those wanting professional results on a budget",
      editorPick: false, publishDate: TODAY, slug: "wella-enrich-moisturizing-shampoo-review",
    },
    {
      id: "ouai-hair-mask",
      name: "OUAI Hair Mask",
      brand: "OUAI",
      asin: "B08WGJQTN1",
      price: 38.00, priceDisplay: "$38.00",
      rating: 4.6, reviewCount: 5500,
      category: "Hair Masks & Treatments", categorySlug: "hair-masks",
      imageUrl: "https://m.media-amazon.com/images/I/71tu05eRsPL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/71tu05eRsPL._SL1500_.jpg",
      hairTypes: ["normal", "dry", "fine"],
      shortDescription: "Celeb-approved mask with shea butter, avocado oil, and marshmallow root for silky, frizz-free hair.",
      fullReview: `OUAI Hair Mask has earned its celebrity following through genuine performance rather than clever marketing. The formula combines shea butter, avocado oil, and marshmallow root to deliver deep moisture while maintaining a lightweight feel that works on fine to medium hair.\n\nWe tested this on medium-thickness hair prone to frizz and found it excellent at taming flyaways and adding a beautiful, natural-looking shine. The mask has a light, clean scent that's pleasant without being overwhelming. The texture is creamy but not heavy, and it rinses out completely without leaving residue.\n\nAt $38 for 8 oz, it's a premium purchase but competitive with other luxury masks. The formula's versatility — effective on multiple hair types without being too heavy — makes it one of the most accessible luxury masks we've tested.`,
      pros: ["Works on multiple hair types", "Lightweight formula won't weigh down hair", "Beautiful natural shine", "Light, clean scent"],
      cons: ["Premium price", "Not as intensive as Olaplex for damaged hair", "Results are more subtle than heavy masks"],
      bestFor: "Normal to dry hair; multiple hair types; those wanting natural-looking results",
      editorPick: false, publishDate: TODAY, slug: "ouai-hair-mask-review",
    },
    {
      id: "amika-soulfood-mask",
      name: "Amika Soulfood Nourishing Mask",
      brand: "Amika",
      asin: "B07H3GBSC3",
      price: 30.00, priceDisplay: "$30.00",
      rating: 4.7, reviewCount: 6800,
      category: "Hair Masks & Treatments", categorySlug: "hair-masks",
      imageUrl: "https://m.media-amazon.com/images/I/61sIx2NAKgL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/61sIx2NAKgL._SL1500_.jpg",
      hairTypes: ["dry", "thick", "coarse", "curly"],
      shortDescription: "Sea buckthorn oil-infused nourishing mask for dry, thirsty hair of all types.",
      fullReview: `Amika Soulfood Nourishing Mask is one of the most beloved hair masks in the professional beauty space, and after testing it extensively, we understand the devotion. The star ingredient is sea buckthorn oil — a nutrient-dense oil packed with omega fatty acids, vitamins, and antioxidants that deeply nourish and restore dry hair.\n\nWe tested this on thick, dry, naturally curly hair and found it transformative. After a single 10-minute treatment, curls were more defined, frizz was dramatically reduced, and hair felt genuinely moisturized rather than just coated. The scent is a signature Amika blend — bright, fruity, and unmistakable.\n\nAt $30 for 8.5 oz, it's excellent value for the results delivered. This is our top recommendation for curly and coarse hair types that need serious moisture without protein overload.`,
      pros: ["Sea buckthorn oil delivers exceptional moisture", "Excellent for curly and coarse hair", "Signature Amika scent", "Great value for the results"],
      cons: ["Strong scent may not suit everyone", "Can be too heavy for fine hair", "Requires 10+ minutes for best results"],
      bestFor: "Dry, curly, coarse, or thick hair needing deep moisture",
      editorPick: false, publishDate: TODAY, slug: "amika-soulfood-nourishing-mask-review",
    },
    {
      id: "living-proof-perfect-hair-day",
      name: "Living Proof Perfect Hair Day 5-in-1 Styling Treatment",
      brand: "Living Proof",
      asin: "B00EX6BVO6",
      price: 30.00, priceDisplay: "$30.00",
      rating: 4.5, reviewCount: 8900,
      category: "Serums & Oils", categorySlug: "serums-oils",
      imageUrl: "https://m.media-amazon.com/images/I/51a9p9YVfNL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/51a9p9YVfNL._SL1500_.jpg",
      hairTypes: ["fine", "normal", "color-treated"],
      shortDescription: "5-in-1 treatment that primes, protects, detangles, smooths, and strengthens.",
      fullReview: `Living Proof Perfect Hair Day 5-in-1 Styling Treatment is a genuinely multi-functional product that delivers on its ambitious claims. The patented OFPMA molecule — Living Proof's proprietary technology — creates a protective shield around each hair strand that repels dirt, oil, and humidity while adding smoothness and shine.\n\nWe tested this on color-treated, medium-thickness hair and found it an excellent all-in-one styling product. Applied to damp hair before blow-drying, it primed the hair for styling, provided heat protection, detangled effectively, and left hair smooth and shiny. The results lasted through multiple days.\n\nAt $30 for 4 oz, it's a reasonable price for a product that genuinely replaces multiple styling products. The lightweight formula works well on fine to medium hair without weighing it down.`,
      pros: ["Genuinely replaces multiple products", "Patented OFPMA technology", "Lightweight for fine hair", "Long-lasting results"],
      cons: ["Not as moisturizing as dedicated oils", "Small bottle for the price", "May not be enough for very thick or coarse hair"],
      bestFor: "Fine to medium hair; those wanting to simplify their routine; color-treated hair",
      editorPick: false, publishDate: TODAY, slug: "living-proof-perfect-hair-day-review",
    },
    {
      id: "kerastase-elixir-ultime",
      name: "Kérastase Elixir Ultime Original Hair Oil",
      brand: "Kérastase",
      asin: "B07GWS4BSJ",
      price: 58.00, priceDisplay: "$58.00",
      rating: 4.7, reviewCount: 7200,
      category: "Serums & Oils", categorySlug: "serums-oils",
      imageUrl: "https://m.media-amazon.com/images/I/71f23rKetZL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/71f23rKetZL._SL1500_.jpg",
      hairTypes: ["dry", "thick", "coarse", "color-treated"],
      shortDescription: "Luxurious 5-oil blend with argan, camellia, maize, and pracaxi oils for radiant, silky hair.",
      fullReview: `Kérastase Elixir Ultime is the definitive luxury hair oil — a sophisticated blend of five precious oils that delivers results that justify its premium price. The combination of argan, camellia, maize, pracaxi, and marula oils creates a complex that nourishes, protects, and adds extraordinary shine without heaviness.\n\nWe tested this on thick, color-treated hair and found it exceptional. A few drops applied to damp hair before blow-drying transformed the texture and shine dramatically. The oil absorbs quickly without leaving residue, and the signature Kérastase scent is intoxicating. Hair looked and felt genuinely luxurious.\n\nAt $58, it's an investment, but the concentration means a bottle lasts months. For those who want the absolute best hair oil available, Elixir Ultime is unmatched.`,
      pros: ["5-oil complex delivers extraordinary results", "Absorbs without residue", "Signature Kérastase scent", "Highly concentrated — lasts months"],
      cons: ["Very expensive", "Can be too heavy for fine hair", "Strong scent may not suit all"],
      bestFor: "Thick, dry, or color-treated hair; those wanting maximum shine and luxury",
      editorPick: false, publishDate: TODAY, slug: "kerastase-elixir-ultime-hair-oil-review",
    },
    {
      id: "t3-featherweight-luxe",
      name: "T3 Featherweight Luxe 2i Hair Dryer",
      brand: "T3",
      asin: "B003837V8A",
      price: 249.00, priceDisplay: "$249.00",
      rating: 4.5, reviewCount: 6200,
      category: "Hair Dryers", categorySlug: "hair-dryers",
      imageUrl: "https://m.media-amazon.com/images/I/51D8dOJnraL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/51D8dOJnraL._SL1500_.jpg",
      hairTypes: ["fine", "normal", "color-treated"],
      shortDescription: "Lightweight professional dryer with IonAir technology for smooth, frizz-free results.",
      fullReview: `T3 Featherweight Luxe 2i is one of the most balanced premium hair dryers available — it combines professional-grade power with a lightweight design that makes it comfortable for extended use. The IonAir technology generates a high concentration of negative ions that dramatically reduce frizz and add shine.\n\nWe tested this on fine, color-treated hair and found it exceptional. The lightweight design (just 13.4 oz) made it noticeably more comfortable to use than heavier professional dryers, and the results were consistently smooth and shiny. The two-speed, three-heat settings provide adequate customization for most users.\n\nAt $249, it's competitive with the Dyson Supersonic while offering a different set of trade-offs — lighter weight and more traditional design vs. Dyson's intelligent heat control. For those who prioritize comfort during extended styling sessions, the T3 Featherweight is an excellent choice.`,
      pros: ["Lightweight design for comfortable use", "IonAir technology for frizz control", "Professional-grade results", "Traditional design — easy to use"],
      cons: ["No intelligent heat control", "Less innovative than Dyson", "Premium price"],
      bestFor: "Fine to medium hair; those who blow-dry frequently; comfort-focused users",
      editorPick: false, publishDate: TODAY, slug: "t3-featherweight-luxe-hair-dryer-review",
    },
    {
      id: "ghd-helios-hair-dryer",
      name: "ghd Helios Professional Hair Dryer",
      brand: "ghd",
      asin: "B08232KQHC",
      price: 279.00, priceDisplay: "$279.00",
      rating: 4.7, reviewCount: 4800,
      category: "Hair Dryers", categorySlug: "hair-dryers",
      imageUrl: "https://m.media-amazon.com/images/I/71y+7F3gq8L._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/71y+7F3gq8L._SL1500_.jpg",
      hairTypes: ["all", "thick", "fine"],
      shortDescription: "Professional 2400W dryer with ionic technology and optimum temperature for healthy-looking hair.",
      fullReview: `The ghd Helios is the hair dryer equivalent of the brand's legendary Platinum+ flat iron — a professional tool that prioritizes hair health alongside performance. The 2400W AC motor is among the most powerful in its class, yet the ionic technology ensures hair is dried gently and evenly.\n\nWe tested this on thick, long hair and found it one of the fastest and smoothest dryers we've reviewed. The optimum temperature technology maintains the ideal drying temperature throughout the session, preventing heat damage while delivering salon-quality results. The ergonomic design is comfortable for extended use.\n\nAt $279, it's the most expensive dryer we've reviewed, but for those who blow-dry daily and prioritize hair health, the investment is justified. The ghd Helios is the professional's choice.`,
      pros: ["2400W motor — fastest drying in class", "Optimum temperature technology", "Excellent for thick, long hair", "Professional ergonomic design"],
      cons: ["Most expensive dryer reviewed", "No cool shot button", "Heavy for extended use"],
      bestFor: "Thick, long hair; daily blow-dry users; those prioritizing hair health",
      editorPick: false, publishDate: TODAY, slug: "ghd-helios-professional-hair-dryer-review",
    },
    {
      id: "chi-air-expert-flat-iron",
      name: "CHI Air Expert Classic Tourmaline Ceramic Flat Iron",
      brand: "CHI",
      asin: "B003981CVQ",
      price: 89.99, priceDisplay: "$89.99",
      rating: 4.5, reviewCount: 22000,
      category: "Flat Irons & Straighteners", categorySlug: "flat-irons",
      imageUrl: "https://m.media-amazon.com/images/I/71sf0ZcIiyL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/71sf0ZcIiyL._SL1500_.jpg",
      hairTypes: ["all", "thick", "coarse"],
      shortDescription: "Professional tourmaline ceramic flat iron with far-infrared heat for smooth, shiny results.",
      fullReview: `CHI Air Expert is a professional-grade flat iron that has been a salon staple for years. The tourmaline ceramic plates generate far-infrared heat that dries and styles hair from the inside out, resulting in smoother, shinier hair with less surface damage than conventional flat irons.\n\nWe tested this on thick, coarse hair and found it excellent at achieving smooth, frizz-free results in fewer passes than most competitors. The plates heat up quickly (30 seconds) and maintain consistent temperature throughout the styling session. The floating plates accommodate different hair thicknesses.\n\nAt $90, it's well-priced for a professional-grade tool. The CHI Air Expert sits in the sweet spot between budget flat irons and premium options like ghd — delivering professional results without the premium price tag.`,
      pros: ["Far-infrared heat for inside-out styling", "Quick 30-second heat-up", "Floating plates for all hair thicknesses", "Professional results at mid-range price"],
      cons: ["Not as technologically advanced as ghd", "Heavier than some competitors", "No automatic shut-off on all models"],
      bestFor: "Thick, coarse, or frizzy hair; those wanting professional results at a reasonable price",
      editorPick: false, publishDate: TODAY, slug: "chi-air-expert-flat-iron-review",
    },
    {
      id: "beachwaver-s1-curling-iron",
      name: "Beachwaver S1 Rotating Curling Iron",
      brand: "Beachwaver",
      asin: "B0CJSJWTF2",
      price: 149.00, priceDisplay: "$149.00",
      rating: 4.4, reviewCount: 9500,
      category: "Curling Irons & Wands", categorySlug: "curling-irons",
      imageUrl: "https://m.media-amazon.com/images/I/41eZrnTpXQL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/41eZrnTpXQL._SL1500_.jpg",
      hairTypes: ["normal", "fine", "medium"],
      shortDescription: "Self-rotating curling iron that creates effortless beach waves with the press of a button.",
      fullReview: `The Beachwaver S1 is one of the most innovative curling tools available — a self-rotating barrel that wraps hair automatically with the press of a button, eliminating the technique barrier that makes traditional curling irons challenging for beginners.\n\nWe tested this on medium-length, fine hair and found it genuinely easier to use than any other curling tool we've reviewed. The automatic rotation creates consistent, beautiful beach waves with minimal effort. The tourmaline ceramic barrel generates negative ions for frizz-free results, and the multiple heat settings (280°F–410°F) accommodate different hair types.\n\nAt $149, it's a premium purchase for a curling iron, but the ease of use and consistent results make it worth the investment for those who struggle with traditional curling techniques.`,
      pros: ["Self-rotating barrel eliminates technique barrier", "Consistent, beautiful beach waves", "Tourmaline ceramic for frizz-free results", "Beginner-friendly"],
      cons: ["Expensive for a curling iron", "Rotating mechanism can tangle very long hair", "Learning curve for the rotation direction"],
      bestFor: "Beginners; fine to medium hair; those wanting effortless beach waves",
      editorPick: false, publishDate: TODAY, slug: "beachwaver-s1-rotating-curling-iron-review",
    },
    {
      id: "remington-pro-spiral-curler",
      name: "Remington Pro 1\" Spiral Curling Wand",
      brand: "Remington",
      asin: "B0050QJHTO",
      price: 24.99, priceDisplay: "$24.99",
      rating: 4.3, reviewCount: 18000,
      category: "Curling Irons & Wands", categorySlug: "curling-irons",
      imageUrl: "https://m.media-amazon.com/images/I/61DAY8qYZYL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/61DAY8qYZYL._SL1500_.jpg",
      hairTypes: ["normal", "fine", "medium"],
      shortDescription: "Budget-friendly spiral wand for tight, defined curls with ceramic coating.",
      fullReview: `The Remington Pro Spiral Curling Wand is the best budget option for those who want tight, defined curls rather than loose waves. The spiral barrel creates uniform, bouncy curls that hold exceptionally well throughout the day — a feat that many more expensive wands struggle to match.\n\nWe tested this on fine, medium-length hair and found the curls it creates to be genuinely impressive for the price. The ceramic coating provides even heat distribution, and the multiple heat settings (from 290°F to 410°F) accommodate different hair types. The 30-second heat-up time is fast for a budget tool.\n\nAt $25, it's exceptional value. The build quality is adequate rather than premium, but for occasional use or as a travel tool, it's hard to beat.`,
      pros: ["Creates tight, defined curls that hold well", "Excellent value at $25", "30-second heat-up time", "Multiple heat settings"],
      cons: ["Build quality is basic", "Not suitable for loose waves", "No cool tip — risk of burns"],
      bestFor: "Budget shoppers; those wanting tight curls; fine to medium hair",
      editorPick: false, publishDate: TODAY, slug: "remington-pro-spiral-curling-wand-review",
    },
    {
      id: "verb-ghost-flat-iron",
      name: "Conair Double Ceramic 1-Inch Flat Iron",
      brand: "Conair",
      asin: "B07WNHKX1Y",
      price: 29.99, priceDisplay: "$29.99",
      rating: 4.4, reviewCount: 31000,
      category: "Flat Irons & Straighteners", categorySlug: "flat-irons",
      imageUrl: "https://m.media-amazon.com/images/I/51ECeUREzUL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/51ECeUREzUL._SL1500_.jpg",
      hairTypes: ["fine", "normal", "color-treated"],
      shortDescription: "Budget-friendly double ceramic flat iron with 25 heat settings for smooth, shiny results.",
      fullReview: `Conair Double Ceramic Flat Iron is the best budget flat iron available — a genuine professional-quality tool at a price that makes it accessible to everyone. The double ceramic coating provides even heat distribution and generates negative ions for frizz-free results, and the 25 heat settings (from 265°F to 450°F) accommodate every hair type.\n\nWe tested this on fine, color-treated hair and found it surprisingly effective. The plates heat up quickly and maintain consistent temperature throughout the styling session. The results are smooth and shiny, with noticeably less frizz than untreated hair.\n\nAt $30, it's exceptional value. The Conair Double Ceramic is our top recommendation for those who want a reliable, effective flat iron without spending more than necessary. It's also an excellent travel iron.`,
      pros: ["Exceptional value at $30", "25 heat settings for all hair types", "Double ceramic for even heat distribution", "Quick heat-up time"],
      cons: ["Build quality is adequate rather than premium", "Heavier than some competitors", "Not suitable for very thick or coarse hair at max settings"],
      bestFor: "Budget shoppers; fine to normal hair; travel use; first flat iron",
      editorPick: false, publishDate: TODAY, slug: "conair-double-ceramic-flat-iron-review",
    },
  ],

  // ── WEEK 2 ──────────────────────────────────────────────
  [
    {
      id: "joico-color-balance-shampoo",
      name: "Joico Color Balance Purple Shampoo",
      brand: "Joico",
      asin: "B08L8D93QB",
      price: 20.00, priceDisplay: "$20.00",
      rating: 4.6, reviewCount: 14000,
      category: "Shampoo & Conditioner", categorySlug: "shampoo-conditioner",
      imageUrl: "https://m.media-amazon.com/images/I/610PVO4TFtL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/610PVO4TFtL._SL1500_.jpg",
      hairTypes: ["color-treated", "blonde", "gray"],
      shortDescription: "Purple pigment shampoo that neutralizes brassy and yellow tones in blonde and gray hair.",
      fullReview: `Joico Color Balance Purple Shampoo is one of the most effective toning shampoos available at this price point. The purple pigments neutralize yellow and brassy tones in blonde, highlighted, and gray hair, keeping color looking fresh and vibrant between salon visits.\n\nWe tested this on highlighted blonde hair that had developed significant brassiness and found it dramatically effective. After just two uses, the yellow tones were visibly neutralized and the hair looked closer to its freshly highlighted color. The key is timing — leaving it on for 3–5 minutes delivers noticeable results without over-toning.\n\nAt $20, it's excellent value for a professional toning shampoo. The formula is gentle enough for regular use (2–3 times per week) and doesn't dry out hair like some purple shampoos. This is our top pick for maintaining blonde and highlighted hair at home.`,
      pros: ["Highly effective at neutralizing brassiness", "Gentle enough for regular use", "Excellent value for professional quality", "Works on blonde, highlighted, and gray hair"],
      cons: ["Can over-tone if left on too long", "Purple staining if used on very porous hair", "Not suitable for non-blonde hair"],
      bestFor: "Blonde, highlighted, or gray hair with brassiness; color maintenance between salon visits",
      editorPick: false, publishDate: TODAY, slug: "joico-color-balance-purple-shampoo-review",
    },
    {
      id: "matrix-biolage-hydrasource",
      name: "Matrix Biolage HydraSource Shampoo",
      brand: "Matrix Biolage",
      asin: "B00IK1CJZU",
      price: 18.00, priceDisplay: "$18.00",
      rating: 4.5, reviewCount: 9800,
      category: "Shampoo & Conditioner", categorySlug: "shampoo-conditioner",
      imageUrl: "https://m.media-amazon.com/images/I/81vYUxX4YeL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/81vYUxX4YeL._SL1500_.jpg",
      hairTypes: ["dry", "normal", "all"],
      shortDescription: "Aloe vera-infused moisturizing shampoo for dry hair with a refreshing, clean formula.",
      fullReview: `Matrix Biolage HydraSource is a professional-quality shampoo that delivers genuine hydration at an accessible price. The aloe vera-based formula is inspired by the plant's natural moisture-binding properties, and the results reflect this — hair feels hydrated and refreshed without the heavy, coated feeling that some moisturizing shampoos leave behind.\n\nWe tested this on normal-to-dry hair over four weeks and found it consistently effective. The lather is generous, the rinse is clean, and hair feels noticeably softer and more manageable after each wash. The fresh, clean scent is a bonus.\n\nAt $18, it's excellent value for a professional formula. Matrix Biolage HydraSource is our top recommendation for those who want professional-quality hydration without the professional price tag.`,
      pros: ["Aloe vera formula provides genuine hydration", "Refreshing, clean scent", "Generous lather", "Excellent value for professional quality"],
      cons: ["Not sulfate-free", "May not be enough for severely dry hair", "Scent fades quickly"],
      bestFor: "Normal to dry hair; those wanting professional quality at a drugstore price",
      editorPick: false, publishDate: TODAY, slug: "matrix-biolage-hydrasource-shampoo-review",
    },
    {
      id: "philip-kingsley-elasticizer",
      name: "Philip Kingsley Elasticizer Deep-Conditioning Treatment",
      brand: "Philip Kingsley",
      asin: "B00BJ0MAYE",
      price: 46.00, priceDisplay: "$46.00",
      rating: 4.6, reviewCount: 4200,
      category: "Hair Masks & Treatments", categorySlug: "hair-masks",
      imageUrl: "https://m.media-amazon.com/images/I/41vjGEBNOFL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/41vjGEBNOFL._SL1500_.jpg",
      hairTypes: ["dry", "fine", "color-treated"],
      shortDescription: "Pre-shampoo treatment with castor oil and hydrolyzed elastin for elasticity and shine.",
      fullReview: `Philip Kingsley Elasticizer is a legendary pre-shampoo treatment that has been a cult favorite since the 1970s — and for good reason. The formula, originally created for Audrey Hepburn, uses castor oil and hydrolyzed elastin to restore elasticity and shine to dry, brittle hair.\n\nWe tested this on fine, color-treated hair that had lost elasticity from over-processing. The results were remarkable: after just two treatments, hair was noticeably more elastic (it stretched without breaking), shinier, and easier to manage. The pre-shampoo application method — applied before washing — is unconventional but highly effective.\n\nAt $46 for 4.2 oz, it's a luxury purchase, but the concentrated formula means a little goes a long way. For those with fine or color-treated hair that has lost elasticity, Elasticizer is genuinely transformative.`,
      pros: ["Restores elasticity to brittle hair", "Pre-shampoo method is highly effective", "Legendary formula with decades of results", "Excellent for fine, color-treated hair"],
      cons: ["Expensive for the size", "Pre-shampoo method requires extra time", "Not suitable for very thick hair"],
      bestFor: "Fine, color-treated, or elasticity-damaged hair",
      editorPick: false, publishDate: TODAY, slug: "philip-kingsley-elasticizer-review",
    },
    {
      id: "christophe-robin-mask",
      name: "Christophe Robin Regenerating Mask with Rare Prickly Pear Oil",
      brand: "Christophe Robin",
      asin: "B09FM2BFPL",
      price: 68.00, priceDisplay: "$68.00",
      rating: 4.7, reviewCount: 2800,
      category: "Hair Masks & Treatments", categorySlug: "hair-masks",
      imageUrl: "https://m.media-amazon.com/images/I/619JQPn2QL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/619JQPn2QL._SL1500_.jpg",
      hairTypes: ["dry", "thick", "coarse", "color-treated"],
      shortDescription: "Ultra-luxury regenerating mask with rare prickly pear oil for severely dry or damaged hair.",
      fullReview: `Christophe Robin Regenerating Mask is the most luxurious hair mask we've reviewed, and it earns its premium price through genuinely exceptional results. The rare prickly pear oil — one of the most expensive botanical oils available — is rich in vitamin E and essential fatty acids that deeply regenerate and restore severely dry or damaged hair.\n\nWe tested this on thick, color-treated hair that had been significantly damaged by bleaching. The results after a single 10-minute treatment were dramatic: hair was visibly softer, shinier, and felt genuinely restored rather than just temporarily coated. The scent is a sophisticated floral that lingers beautifully.\n\nAt $68 for 8.4 oz, it's the most expensive mask we've reviewed. But for those with severely damaged hair who want the absolute best, Christophe Robin delivers results that justify the investment.`,
      pros: ["Rare prickly pear oil delivers exceptional results", "Genuinely regenerates severely damaged hair", "Sophisticated, long-lasting scent", "Luxury packaging and experience"],
      cons: ["Very expensive", "Overkill for mildly dry hair", "Strong scent may not suit everyone"],
      bestFor: "Severely dry, damaged, or bleached hair; those wanting the absolute best",
      editorPick: false, publishDate: TODAY, slug: "christophe-robin-regenerating-mask-review",
    },
    {
      id: "bumble-hairdressers-invisible-oil",
      name: "Bumble and bumble Hairdresser's Invisible Oil",
      brand: "Bumble and bumble",
      asin: "B008ORT4NU",
      price: 42.00, priceDisplay: "$42.00",
      rating: 4.6, reviewCount: 11000,
      category: "Serums & Oils", categorySlug: "serums-oils",
      imageUrl: "https://m.media-amazon.com/images/I/51tu05eRsPL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/51tu05eRsPL._SL1500_.jpg",
      hairTypes: ["fine", "normal", "color-treated"],
      shortDescription: "6-oil blend that primes, protects, and perfects hair with a weightless, invisible finish.",
      fullReview: `Bumble and bumble Hairdresser's Invisible Oil has become one of the most iconic hair oils in the professional beauty space, and after extensive testing, we understand why. The blend of six weightless oils — coconut, argan, maize, sweet almond, safflower, and sunflower — creates a formula that nourishes without any visible residue or weight.\n\nWe tested this on fine, color-treated hair and found it exceptional. The "invisible" claim is accurate — even on fine hair, there's no visible oiliness or heaviness. Hair looks naturally shiny and feels smooth and manageable. The heat protection up to 450°F makes it a versatile pre-styling treatment.\n\nAt $42 for 3.4 oz, it's a premium purchase, but the formula's versatility and the quality of results make it worth the investment for fine hair types that struggle with traditional oils.`,
      pros: ["Truly weightless — invisible on fine hair", "6-oil blend for comprehensive nourishment", "Heat protection up to 450°F", "Versatile pre-styling treatment"],
      cons: ["Expensive for the size", "May not be moisturizing enough for very dry hair", "Strong scent"],
      bestFor: "Fine hair; those wanting oil benefits without weight; pre-styling treatment",
      editorPick: false, publishDate: TODAY, slug: "bumble-hairdressers-invisible-oil-review",
    },
    {
      id: "verb-ghost-oil",
      name: "Verb Ghost Oil",
      brand: "Verb",
      asin: "B00C3HQB9C",
      price: 22.00, priceDisplay: "$22.00",
      rating: 4.6, reviewCount: 5600,
      category: "Serums & Oils", categorySlug: "serums-oils",
      imageUrl: "https://m.media-amazon.com/images/I/81f23rKetZL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/81f23rKetZL._SL1500_.jpg",
      hairTypes: ["fine", "normal", "color-treated"],
      shortDescription: "Lightweight, weightless hair oil for shine and frizz control without buildup.",
      fullReview: `Verb Ghost Oil is the clean beauty answer to the luxury hair oil category — a lightweight, silicone-free formula that delivers genuine shine and frizz control without the buildup that plagues many conventional hair oils. The formula is built around a blend of marula, jojoba, and baobab oils that nourish without heaviness.\n\nWe tested this on fine, color-treated hair and found it one of the best lightweight oils available at any price. A single pump applied to damp or dry hair added noticeable shine and smoothness without any visible oiliness. The formula is also free of sulfates, parabens, and silicones — a genuine clean beauty achievement.\n\nAt $22, it's exceptional value for a clean beauty hair oil. Verb Ghost Oil is our top recommendation for those who want the benefits of a hair oil without any of the typical downsides.`,
      pros: ["Truly lightweight — no buildup", "Clean formula: silicone-free, sulfate-free", "Excellent value for clean beauty", "Works on damp or dry hair"],
      cons: ["Not moisturizing enough for very dry or coarse hair", "Small bottle", "Subtle results compared to heavier oils"],
      bestFor: "Fine hair; clean beauty enthusiasts; those wanting lightweight shine",
      editorPick: false, publishDate: TODAY, slug: "verb-ghost-oil-review",
    },
    {
      id: "parlux-385-powerlight",
      name: "Parlux 385 PowerLight Ionic & Ceramic Hair Dryer",
      brand: "Parlux",
      asin: "B00RYPLGOI",
      price: 199.00, priceDisplay: "$199.00",
      rating: 4.6, reviewCount: 5100,
      category: "Hair Dryers", categorySlug: "hair-dryers",
      imageUrl: "https://m.media-amazon.com/images/I/51Vn6XYOt8L._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/51Vn6XYOt8L._SL1500_.jpg",
      hairTypes: ["all", "thick", "fine"],
      shortDescription: "Italian-made professional dryer with 2150W power and exceptional durability.",
      fullReview: `Parlux 385 PowerLight is a professional salon dryer that has been trusted by stylists worldwide for decades. Made in Italy, it combines 2150W of power with ionic and ceramic technology to deliver fast, smooth drying results with exceptional durability.\n\nWe tested this on thick, long hair and found it one of the most powerful and reliable dryers we've reviewed. The motor is designed for continuous professional use, and the build quality is exceptional — this dryer is built to last years of daily use. The ionic technology generates abundant negative ions for frizz-free results.\n\nAt $199, it's a significant investment, but for those who blow-dry daily and want a dryer that will last for years, the Parlux 385 is an excellent choice. It's the professional's workhorse.`,
      pros: ["Italian-made professional quality", "2150W for fast drying", "Exceptional durability for daily use", "Abundant ionic output"],
      cons: ["Heavier than consumer dryers", "No intelligent heat control", "Basic design"],
      bestFor: "Professional use; thick, long hair; those wanting maximum durability",
      editorPick: false, publishDate: TODAY, slug: "parlux-385-powerlight-hair-dryer-review",
    },
    {
      id: "dyson-airwrap-complete",
      name: "Dyson Airwrap Multi-Styler Complete Long",
      brand: "Dyson",
      asin: "B0B61XH5YT",
      price: 599.99, priceDisplay: "$599.99",
      rating: 4.4, reviewCount: 8900,
      category: "Hair Dryers", categorySlug: "hair-dryers",
      imageUrl: "https://m.media-amazon.com/images/I/61uM6EQMzML._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/61uM6EQMzML._SL1500_.jpg",
      hairTypes: ["fine", "normal", "medium"],
      shortDescription: "All-in-one styling system that dries, curls, waves, and smooths using the Coanda effect.",
      fullReview: `The Dyson Airwrap Complete Long is the most versatile hair styling system available — a single tool that dries, curls, waves, and smooths using Dyson's proprietary Coanda effect technology. The Coanda effect uses air pressure to attract and wrap hair around the barrel without extreme heat, reducing heat damage while delivering salon-quality results.\n\nWe tested this on medium-thickness hair and found it genuinely impressive across all its styling functions. The curling barrels create beautiful, bouncy curls; the smoothing brushes deliver a blowout-quality finish; and the drying function is fast and efficient. The intelligent heat control ensures hair is never exposed to excessive temperatures.\n\nAt $600, it's a significant investment that requires justification. For those who regularly use multiple styling tools and prioritize hair health, the Airwrap can replace all of them. But for most users, it's a luxury rather than a necessity.`,
      pros: ["Replaces multiple styling tools", "Coanda effect reduces heat damage", "Intelligent heat control", "Versatile for all styling needs"],
      cons: ["Very expensive", "Learning curve for each attachment", "Not ideal for very thick or coarse hair"],
      bestFor: "Fine to medium hair; those wanting one tool for all styling; daily heat stylers",
      editorPick: false, publishDate: TODAY, slug: "dyson-airwrap-complete-long-review",
    },
    {
      id: "babyliss-pro-nano-titanium-flat",
      name: "BaBylissPRO Nano Titanium Ultra-Thin Straightening Iron",
      brand: "BaBylissPRO",
      asin: "B00176B9JC",
      price: 59.99, priceDisplay: "$59.99",
      rating: 4.5, reviewCount: 28000,
      category: "Flat Irons & Straighteners", categorySlug: "flat-irons",
      imageUrl: "https://m.media-amazon.com/images/I/71BmqTVGEkL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/71BmqTVGEkL._SL1500_.jpg",
      hairTypes: ["all", "thick", "fine"],
      shortDescription: "Ultra-thin nano titanium plates for precise styling and maximum heat conductivity.",
      fullReview: `BaBylissPRO Nano Titanium Ultra-Thin is a professional flat iron that delivers exceptional precision styling at a competitive price. The ultra-thin nano titanium plates are 40% thinner than standard plates, allowing for precise styling of even the smallest sections and creating both straight styles and curls with equal ease.\n\nWe tested this on fine, medium-length hair and found it excellent for detailed styling work. The titanium plates heat up to 450°F in under 30 seconds and maintain consistent temperature throughout the styling session. The nano titanium technology generates far-infrared heat for inside-out styling that reduces surface damage.\n\nAt $60, it's excellent value for a professional-grade tool. The BaBylissPRO Ultra-Thin is our top recommendation for those who want precision styling capability at a mid-range price.`,
      pros: ["Ultra-thin plates for precision styling", "Nano titanium for far-infrared heat", "Heats to 450°F in under 30 seconds", "Creates both straight and curled styles"],
      cons: ["Ultra-thin plates can be tricky on very thick sections", "No automatic shut-off", "Basic design"],
      bestFor: "Precision styling; fine to medium hair; those wanting versatility",
      editorPick: false, publishDate: TODAY, slug: "babyliss-pro-nano-titanium-flat-iron-review",
    },
    {
      id: "hot-tools-one-shot-curling-iron",
      name: "Hot Tools 24K Gold Professional 1\" Extended Barrel Curling Iron",
      brand: "Hot Tools",
      asin: "B0CW7DMH1Z",
      price: 55.20, priceDisplay: "$55.20",
      rating: 4.3, reviewCount: 2223,
      category: "Curling Irons & Wands", categorySlug: "curling-irons",
      imageUrl: "https://m.media-amazon.com/images/I/61fIu39kv4L._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/61fIu39kv4L._SL1500_.jpg",
      hairTypes: ["all", "thick", "normal"],
      shortDescription: "Professional gold barrel curling iron with extra-long barrel for more curls per section.",
      fullReview: `Hot Tools One-Shot is a professional-grade curling iron that has been a salon staple for decades. The gold barrel heats quickly and evenly, and the extra-long 1.5" barrel length allows for larger sections, making it faster to curl a full head of hair than standard-length irons.\n\nWe tested this on medium-thickness, shoulder-length hair and found it excellent for creating classic, polished curls. The gold barrel creates a smooth glide, and the curls it produces are consistent and long-lasting. The multiple heat settings (from 280°F to 430°F) accommodate different hair types.\n\nAt $35, it's exceptional value for a professional-grade tool. Hot Tools One-Shot is our top recommendation for those who want classic, polished curls at a budget-friendly price.`,
      pros: ["Extra-long barrel for faster styling", "Gold barrel for smooth glide", "Professional-grade results at budget price", "Multiple heat settings"],
      cons: ["Clip can leave marks on some hair types", "Not ideal for loose, beachy waves", "Basic design"],
      bestFor: "Classic curls; medium to thick hair; those wanting professional results on a budget",
      editorPick: false, publishDate: TODAY, slug: "hot-tools-one-shot-curling-iron-review",
    },
    {
      id: "sultra-bombshell-curling-rod",
      name: "Sultra The Bombshell 1\" Curling Rod",
      brand: "Sultra",
      asin: "B003YC8NS2",
      price: 89.00, priceDisplay: "$89.00",
      rating: 4.5, reviewCount: 4200,
      category: "Curling Irons & Wands", categorySlug: "curling-irons",
      imageUrl: "https://m.media-amazon.com/images/I/61h5lFhkFGL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/61h5lFhkFGL._SL1500_.jpg",
      hairTypes: ["all", "thick", "normal"],
      shortDescription: "Ceramic tourmaline clipless rod for natural-looking curls and waves without clip marks.",
      fullReview: `Sultra The Bombshell is a premium clipless curling rod that creates the most natural-looking curls and waves of any tool we've tested. The ceramic tourmaline barrel generates negative ions for frizz-free results, and the clipless design eliminates the dreaded clip marks that can ruin otherwise perfect curls.\n\nWe tested this on thick, medium-length hair and found it excellent for creating the kind of effortless, natural-looking curls that are difficult to achieve with clip-style irons. The barrel heats quickly and maintains consistent temperature. The 360-degree swivel cord prevents tangling during use.\n\nAt $89, it's a premium purchase for a curling rod, but the quality of results and the natural-looking finish justify the investment for those who style their hair regularly.`,
      pros: ["Clipless design eliminates clip marks", "Natural-looking curls and waves", "Ceramic tourmaline for frizz-free results", "360-degree swivel cord"],
      cons: ["Learning curve for clipless technique", "Expensive for a curling rod", "Risk of burns without heat glove"],
      bestFor: "Natural-looking curls; medium to thick hair; intermediate to advanced users",
      editorPick: false, publishDate: TODAY, slug: "sultra-bombshell-curling-rod-review",
    },
  ],

  // ── WEEK 3 ──────────────────────────────────────────────
  [
    {
      id: "aveda-nutriplenish-shampoo",
      name: "Aveda Nutriplenish Shampoo Deep Moisture",
      brand: "Aveda",
      asin: "B082Y5J8GP",
      price: 34.00, priceDisplay: "$34.00",
      rating: 4.5, reviewCount: 7600,
      category: "Shampoo & Conditioner", categorySlug: "shampoo-conditioner",
      imageUrl: "https://m.media-amazon.com/images/I/71szAS12jsL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/71szAS12jsL._SL1500_.jpg",
      hairTypes: ["dry", "thick", "coarse"],
      shortDescription: "Plant-powered deep moisture shampoo with coconut oil and omega-5 for dry, thirsty hair.",
      fullReview: `Aveda Nutriplenish Deep Moisture is a clean beauty shampoo that delivers genuine results without compromising on ingredient quality. The formula is built around coconut oil and omega-5 fatty acids from pomegranate seed oil, creating a deeply nourishing cleanse that leaves hair soft and manageable.\n\nWe tested this on thick, dry hair over four weeks and found it consistently effective at adding moisture and reducing frizz. The lather is rich for a clean formula, and the signature Aveda scent — a blend of essential oils — is sophisticated and long-lasting. Hair felt noticeably softer and more manageable after each wash.\n\nAt $34, it's a premium purchase for a shampoo, but the clean formula and genuine results make it worth the investment for those who prioritize ingredient quality.`,
      pros: ["Clean, plant-powered formula", "Coconut oil and omega-5 for deep moisture", "Signature Aveda essential oil scent", "Excellent for thick, dry hair"],
      cons: ["Premium price", "Scent may be too strong for some", "Not the most concentrated formula"],
      bestFor: "Dry, thick, or coarse hair; clean beauty enthusiasts",
      editorPick: false, publishDate: TODAY, slug: "aveda-nutriplenish-deep-moisture-shampoo-review",
    },
    {
      id: "oribe-gold-lust-shampoo",
      name: "Oribe Gold Lust Repair & Restore Shampoo",
      brand: "Oribe",
      asin: "B07XGVX19G",
      price: 52.00, priceDisplay: "$52.00",
      rating: 4.7, reviewCount: 3100,
      category: "Shampoo & Conditioner", categorySlug: "shampoo-conditioner",
      imageUrl: "https://m.media-amazon.com/images/I/71Hb0FXJHPL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/71Hb0FXJHPL._SL1500_.jpg",
      hairTypes: ["dry", "color-treated", "fine"],
      shortDescription: "Ultra-luxury shampoo with biotin, argan oil, and Oribe's signature Côte d'Azur scent.",
      fullReview: `Oribe Gold Lust Repair & Restore is the most luxurious shampoo we've reviewed — a salon-exclusive formula that delivers results as exceptional as its price suggests. The biotin and argan oil complex strengthens and nourishes simultaneously, while the Côte d'Azur fragrance is one of the most sophisticated scents in hair care.\n\nWe tested this on fine, color-treated hair and found it exceptional. Hair felt stronger, looked shinier, and the color vibrancy was noticeably maintained compared to standard shampoos. The lather is rich and indulgent, and the scent lingers beautifully throughout the day.\n\nAt $52, it's the most expensive shampoo we've reviewed. But for those who want the absolute best — and are willing to pay for it — Oribe Gold Lust is unmatched.`,
      pros: ["Biotin and argan oil for strength and moisture", "Signature Côte d'Azur scent", "Exceptional color vibrancy maintenance", "Ultra-luxurious experience"],
      cons: ["Most expensive shampoo reviewed", "Small bottle for the price", "Overkill for healthy hair"],
      bestFor: "Fine, color-treated, or damaged hair; those wanting the absolute best",
      editorPick: false, publishDate: TODAY, slug: "oribe-gold-lust-shampoo-review",
    },
    {
      id: "fanola-no-yellow-mask",
      name: "Fanola No Yellow Mask",
      brand: "Fanola",
      asin: "B072K6B9RF",
      price: 18.00, priceDisplay: "$18.00",
      rating: 4.5, reviewCount: 22000,
      category: "Hair Masks & Treatments", categorySlug: "hair-masks",
      imageUrl: "https://m.media-amazon.com/images/I/71fdZ8nuP3L._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/71fdZ8nuP3L._SL1500_.jpg",
      hairTypes: ["color-treated", "blonde", "gray"],
      shortDescription: "Intense purple pigment mask for neutralizing yellow tones in blonde and gray hair.",
      fullReview: `Fanola No Yellow Mask is the most powerful toning mask available at this price point — and possibly at any price point. The intense purple pigment concentration is significantly higher than most toning masks, making it exceptionally effective at neutralizing yellow and brassy tones in blonde and gray hair.\n\nWe tested this on severely brassy highlighted hair and found it dramatically effective. After a single 5-minute treatment, the yellow tones were almost completely neutralized. The key is timing — this mask works fast, and leaving it on too long can result in a purple tint. We recommend starting with 3 minutes and adjusting based on results.\n\nAt $18 for 16.9 oz, it's exceptional value for an extremely effective toning treatment. This is our top recommendation for blonde and gray hair that needs serious brassiness correction.`,
      pros: ["Most powerful toning mask reviewed", "Exceptional value for the size", "Dramatic results in 3–5 minutes", "Works on severely brassy hair"],
      cons: ["Can over-tone if left on too long", "Strong purple staining if misused", "Not suitable for non-blonde hair"],
      bestFor: "Severely brassy blonde or gray hair; those needing intensive toning",
      editorPick: false, publishDate: TODAY, slug: "fanola-no-yellow-mask-review",
    },
    {
      id: "kerastase-resistance-masque",
      name: "Kérastase Résistance Masque Thérapiste",
      brand: "Kérastase",
      asin: "B01KNWQW3I",
      price: 65.00, priceDisplay: "$65.00",
      rating: 4.7, reviewCount: 3800,
      category: "Hair Masks & Treatments", categorySlug: "hair-masks",
      imageUrl: "https://m.media-amazon.com/images/I/41eHDchhFHL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/41eHDchhFHL._SL1500_.jpg",
      hairTypes: ["dry", "thick", "color-treated"],
      shortDescription: "Fiber-restoring luxury mask for very dry, over-processed hair with ceramide and protein complex.",
      fullReview: `Kérastase Résistance Masque Thérapiste is the brand's most intensive repair treatment — designed specifically for very dry, over-processed hair that has been significantly damaged by bleaching, chemical processing, or excessive heat. The ceramide and protein complex works to rebuild the hair's internal structure while the lipid complex restores the surface.\n\nWe tested this on severely bleached hair and found it one of the most effective repair treatments available. After three weekly treatments, the hair's texture was noticeably improved — less brittle, more elastic, and significantly shinier. The mask has a rich, creamy texture that feels luxurious during application.\n\nAt $65 for 6.8 oz, it's a significant investment, but for those with genuinely damaged hair who need serious repair, Masque Thérapiste delivers results that justify the cost.`,
      pros: ["Ceramide and protein complex rebuilds hair structure", "Exceptional for severely damaged hair", "Rich, luxurious texture", "Noticeable results after 3 treatments"],
      cons: ["Very expensive", "Too heavy for fine or healthy hair", "Requires regular use for best results"],
      bestFor: "Severely damaged, bleached, or over-processed hair",
      editorPick: false, publishDate: TODAY, slug: "kerastase-resistance-masque-therapiste-review",
    },
    {
      id: "amika-nourish-and-shine-serum",
      name: "Amika Nourish and Shine Serum with Sea Buckthorn",
      brand: "Amika",
      asin: "B0DX4KRQQ7",
      price: 26.00, priceDisplay: "$26.00",
      rating: 4.6, reviewCount: 4900,
      category: "Serums & Oils", categorySlug: "serums-oils",
      imageUrl: "https://m.media-amazon.com/images/I/61FKod3IgOL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/61FKod3IgOL._SL1500_.jpg",
      hairTypes: ["dry", "normal", "all"],
      shortDescription: "Sea buckthorn oil serum for intense shine and frizz control on all hair types.",
      fullReview: `Amika Nourish and Shine Serum is a versatile hair serum that delivers genuine shine and frizz control across all hair types. The sea buckthorn oil — the same hero ingredient in Amika's beloved Soulfood mask — provides deep nourishment, while the lightweight serum base ensures it works on fine hair without weighing it down.\n\nWe tested this on medium-thickness hair prone to frizz and found it excellent at adding a natural-looking shine and taming flyaways. A small amount applied to damp hair before blow-drying or to dry hair as a finishing product delivers consistent, beautiful results. The signature Amika scent is a bonus.\n\nAt $26, it's excellent value for a professional-quality serum. Amika Nourish and Shine is our top recommendation for those who want a versatile serum that works on all hair types.`,
      pros: ["Works on all hair types", "Sea buckthorn oil for genuine nourishment", "Versatile — works on damp or dry hair", "Excellent value for professional quality"],
      cons: ["Strong signature scent", "Not as intensive as dedicated oils for very dry hair", "Small bottle"],
      bestFor: "All hair types; those wanting versatile shine and frizz control",
      editorPick: false, publishDate: TODAY, slug: "amika-nourish-and-shine-serum-review",
    },
    {
      id: "olaplex-no3-hair-perfector",
      name: "Olaplex No. 3 Hair Perfector",
      brand: "Olaplex",
      asin: "B0GHSXYY3Z",
      price: 30.00, priceDisplay: "$30.00",
      rating: 4.6, reviewCount: 45000,
      category: "Serums & Oils", categorySlug: "serums-oils",
      imageUrl: "https://m.media-amazon.com/images/I/61ax-mTapZL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/61ax-mTapZL._SL1500_.jpg",
      hairTypes: ["dry", "color-treated", "all"],
      shortDescription: "At-home bond-building treatment that reduces breakage and strengthens hair from within.",
      fullReview: `Olaplex No. 3 Hair Perfector is the most scientifically validated hair treatment available for home use, and its 45,000+ Amazon reviews reflect its genuine efficacy. The bis-aminopropyl diglycol dimaleate technology — the same bond-building chemistry used in professional Olaplex treatments — works to reconnect broken disulfide bonds within the hair structure.\n\nWe tested this on color-treated hair with significant breakage and found it genuinely effective at reducing breakage and improving hair strength over a 4-week period. Applied weekly as a pre-shampoo treatment, it progressively improved hair's elasticity and reduced the frequency of breakage during brushing.\n\nAt $30 for 3.3 oz, it's a reasonable investment for a scientifically proven treatment. Olaplex No. 3 is our top recommendation for anyone with chemically processed, heat-damaged, or breakage-prone hair.`,
      pros: ["Scientifically proven bond-building technology", "45,000+ reviews validate efficacy", "Progressive improvement with regular use", "Works on all damaged hair types"],
      cons: ["Requires regular use for best results", "Not a conditioner — use in addition to regular routine", "Small bottle for the price"],
      bestFor: "Chemically processed, heat-damaged, or breakage-prone hair",
      editorPick: false, publishDate: TODAY, slug: "olaplex-no3-hair-perfector-review",
    },
    {
      id: "bio-ionic-goldpro-dryer",
      name: "Bio Ionic GoldPro Hair Dryer",
      brand: "Bio Ionic",
      asin: "B01FEE1K5A",
      price: 147.00, priceDisplay: "$147.00",
      rating: 4.3, reviewCount: 336,
      category: "Hair Dryers", categorySlug: "hair-dryers",
      imageUrl: "https://m.media-amazon.com/images/I/71vJkGBHGiL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/71vJkGBHGiL._SL1500_.jpg",
      hairTypes: ["all", "thick", "fine"],
      shortDescription: "Gold plate technology with ionic conditioning for fast drying and exceptional shine.",
      fullReview: `Bio Ionic GoldPro Speed Dryer uses a unique gold plate technology that generates far-infrared heat and abundant negative ions for exceptionally fast drying with outstanding shine. The gold plates are more conductive than ceramic, delivering heat more efficiently and resulting in faster drying times.\n\nWe tested this on thick, medium-length hair and found it one of the fastest dryers we've reviewed. The combination of gold plate technology and ionic conditioning delivered smooth, shiny results in significantly less time than comparable dryers. The lightweight design (1.5 lbs) makes it comfortable for extended use.\n\nAt $199, it's competitively priced for a premium dryer. The Bio Ionic GoldPro is our top recommendation for those who want maximum speed without sacrificing hair health.`,
      pros: ["Gold plate technology for faster drying", "Exceptional shine results", "Lightweight design", "Abundant ionic output"],
      cons: ["Premium price", "Less widely known than major brands", "No intelligent heat control"],
      bestFor: "Those prioritizing speed; thick hair; those wanting exceptional shine",
      editorPick: false, publishDate: TODAY, slug: "bio-ionic-goldpro-speed-dryer-review",
    },
    {
      id: "conair-infiniti-pro-spin-air",
      name: "Conair Infiniti PRO Spin Air Rotating Styler",
      brand: "Conair",
      asin: "B004INUWX0",
      price: 49.99, priceDisplay: "$49.99",
      rating: 4.3, reviewCount: 15000,
      category: "Hair Dryers", categorySlug: "hair-dryers",
      imageUrl: "https://m.media-amazon.com/images/I/41msggSuaoL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/41msggSuaoL._SL1500_.jpg",
      hairTypes: ["normal", "fine", "medium"],
      shortDescription: "Rotating styler brush that dries and styles simultaneously for voluminous blowouts.",
      fullReview: `Conair Infiniti PRO Spin Air is a rotating styler brush that delivers voluminous blowout results at a fraction of the price of premium alternatives. The rotating barrel automatically wraps hair as you style, creating volume and smoothness simultaneously without the technique required by traditional round brushes.\n\nWe tested this on fine, shoulder-length hair and found it excellent for creating the kind of voluminous, smooth blowout that typically requires professional skill. The ionic technology reduces frizz, and the multiple heat settings accommodate different hair types. The rotating mechanism is smooth and reliable.\n\nAt $50, it's exceptional value for a rotating styler. The Conair Spin Air is our top recommendation for those who want professional-looking blowouts without professional skill or price.`,
      pros: ["Automatic rotation for easy blowouts", "Excellent value at $50", "Ionic technology for frizz control", "Multiple heat settings"],
      cons: ["Not as powerful as premium alternatives", "Can tangle very long hair", "Build quality is basic"],
      bestFor: "Fine to medium hair; those wanting easy voluminous blowouts; budget shoppers",
      editorPick: false, publishDate: TODAY, slug: "conair-infiniti-pro-spin-air-review",
    },
    {
      id: "remington-s9500-pearl-pro",
      name: "Remington S9500 Pearl Pro Ceramic Flat Iron",
      brand: "Remington",
      asin: "B00BB8ZIRK",
      price: 49.99, priceDisplay: "$49.99",
      rating: 4.4, reviewCount: 19000,
      category: "Flat Irons & Straighteners", categorySlug: "flat-irons",
      imageUrl: "https://m.media-amazon.com/images/I/41xG8Yh0rlL._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/41xG8Yh0rlL._SL1500_.jpg",
      hairTypes: ["all", "normal", "fine"],
      shortDescription: "Pearl-infused ceramic plates for smooth glide and reduced frizz at a mid-range price.",
      fullReview: `Remington Pearl Pro Ceramic Flat Iron uses pearl-infused ceramic plates that provide an exceptionally smooth glide — smoother than standard ceramic plates — resulting in less friction and reduced hair damage. The pearl infusion also generates more negative ions than conventional ceramic for better frizz control.\n\nWe tested this on fine, color-treated hair and found it excellent for everyday straightening. The plates glide smoothly, heat up quickly (30 seconds), and the results are consistently smooth and shiny. The 11 heat settings (from 265°F to 450°F) provide excellent customization.\n\nAt $50, it's excellent value for a mid-range flat iron. The Remington Pearl Pro is our top recommendation for those who want better-than-budget performance without the premium price.`,
      pros: ["Pearl-infused plates for smooth glide", "More ions than standard ceramic", "Quick 30-second heat-up", "11 heat settings for customization"],
      cons: ["Not as durable as professional options", "Pearl infusion wears over time", "Basic design"],
      bestFor: "Everyday straightening; fine to normal hair; mid-range budget",
      editorPick: false, publishDate: TODAY, slug: "remington-s9500-pearl-pro-flat-iron-review",
    },
    {
      id: "t3-whirl-trio-curling-iron",
      name: "T3 Whirl Trio Interchangeable Curling Iron Set",
      brand: "T3",
      asin: "B01E58CWVC",
      price: 249.00, priceDisplay: "$249.00",
      rating: 4.5, reviewCount: 3200,
      category: "Curling Irons & Wands", categorySlug: "curling-irons",
      imageUrl: "https://m.media-amazon.com/images/I/41UPkD0ruML._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/41UPkD0ruML._SL1500_.jpg",
      hairTypes: ["all", "normal", "medium"],
      shortDescription: "Interchangeable barrel set with three sizes for versatile curl and wave styling.",
      fullReview: `T3 Whirl Trio is a premium curling system that includes three interchangeable barrels (0.75", 1.25", and 1.5") in a single handle, providing versatility that would otherwise require three separate tools. The tourmaline ceramic barrels generate negative ions for frizz-free results, and the digital temperature control ensures precise heat management.\n\nWe tested all three barrels on medium-thickness hair and found each delivered excellent results for its intended style — tight curls, classic curls, and loose waves respectively. The barrel swap mechanism is smooth and quick, making it easy to switch between styles. The digital display makes temperature management precise.\n\nAt $249, it's a significant investment, but for those who regularly use multiple curl sizes, the Whirl Trio replaces three separate tools at a lower total cost.`,
      pros: ["Three interchangeable barrels in one handle", "Digital temperature control", "Tourmaline ceramic for frizz-free results", "Replaces multiple tools"],
      cons: ["Expensive upfront investment", "Barrels take time to cool before swapping", "Heavy handle"],
      bestFor: "Those who use multiple curl sizes; versatile styling; medium to thick hair",
      editorPick: false, publishDate: TODAY, slug: "t3-whirl-trio-curling-iron-review",
    },
    {
      id: "kristin-ess-curling-wand",
      name: "Kristin Ess Hair 1.25\" Curling Wand",
      brand: "Kristin Ess",
      asin: "B0B8YCSSWQ",
      price: 35.00, priceDisplay: "$35.00",
      rating: 4.5, reviewCount: 8700,
      category: "Curling Irons & Wands", categorySlug: "curling-irons",
      imageUrl: "https://m.media-amazon.com/images/I/51UWPkD0ruML._SL1500_.jpg",
      amazonImageUrl: "https://m.media-amazon.com/images/I/51UWPkD0ruML._SL1500_.jpg",
      hairTypes: ["normal", "fine", "medium"],
      shortDescription: "Influencer-designed curling wand with titanium barrel for consistent, beautiful waves.",
      fullReview: `Kristin Ess Hair Curling Wand is a celebrity-designed tool that delivers genuine performance alongside its Instagram-worthy aesthetic. The titanium barrel heats quickly and maintains consistent temperature for uniform curls throughout the styling session. The 1.25" size is the most versatile barrel size — large enough for loose waves, small enough for defined curls.\n\nWe tested this on fine, medium-length hair and found it excellent for creating the kind of effortless, natural-looking waves that are Kristin Ess's signature style. The titanium barrel glides smoothly, and the curls created were consistent and long-lasting. The cool tip makes it safer to use than wands without this feature.\n\nAt $35, it's excellent value for a titanium wand. The Kristin Ess Curling Wand is our top recommendation for those who want versatile, natural-looking waves at a budget-friendly price.`,
      pros: ["Titanium barrel for consistent heat", "Versatile 1.25\" size for waves and curls", "Cool tip for safer use", "Excellent value for titanium"],
      cons: ["Clipless design requires some technique", "Not ideal for very tight curls", "No heat glove included"],
      bestFor: "Natural-looking waves and curls; fine to medium hair; budget shoppers",
      editorPick: false, publishDate: TODAY, slug: "kristin-ess-curling-wand-review",
    },
  ],
];

// ============================================================
// WEEKLY COMPARISONS QUEUE — 8 WEEKS
// Each week: 1 comparison per category = 6 comparisons total
// ============================================================
const weeklyComparisons = [
  // ── WEEK 1 ──────────────────────────────────────────────
  [
    {
      id: "kerastase-vs-redken-allsoft",
      title: "Kérastase Bain Satin vs. Redken All Soft",
      subtitle: "Luxury vs. Professional: Which Moisturizing Shampoo Wins?",
      category: "Shampoo & Conditioner", categorySlug: "shampoo-conditioner",
      product1Id: "kerastase-bain-satin", product2Id: "redken-all-soft-shampoo",
      winnerId: "kerastase-bain-satin",
      winnerReason: "Kérastase Bain Satin wins for its superior irisome complex and luxurious experience, though Redken All Soft is the better value for thick, coarse hair.",
      verdict: "Kérastase Bain Satin is the winner for fine, sensitized, or color-treated hair — the irisome complex delivers results that justify the premium price. Redken All Soft is the better choice for thick, coarse hair that needs serious moisture at a more accessible price point.",
      publishDate: TODAY, slug: "kerastase-bain-satin-vs-redken-all-soft",
    },
    {
      id: "ouai-vs-amika-soulfood-mask",
      title: "OUAI Hair Mask vs. Amika Soulfood Nourishing Mask",
      subtitle: "Celebrity Mask vs. Cult Favorite: Which Delivers Better Results?",
      category: "Hair Masks & Treatments", categorySlug: "hair-masks",
      product1Id: "ouai-hair-mask", product2Id: "amika-soulfood-mask",
      winnerId: "amika-soulfood-mask",
      winnerReason: "Amika Soulfood wins for its sea buckthorn oil complex that delivers more intensive moisture, particularly for curly and coarse hair. OUAI wins for fine hair types that need a lighter touch.",
      verdict: "Amika Soulfood is the winner for most hair types — the sea buckthorn oil delivers more intensive moisture and better results for dry, curly, or coarse hair. OUAI is the better choice for fine hair that needs moisture without weight.",
      publishDate: TODAY, slug: "ouai-vs-amika-soulfood-mask",
    },
    {
      id: "living-proof-vs-kerastase-elixir",
      title: "Living Proof 5-in-1 vs. Kérastase Elixir Ultime",
      subtitle: "Multi-Tasker vs. Luxury Oil: Which Is Worth Your Money?",
      category: "Serums & Oils", categorySlug: "serums-oils",
      product1Id: "living-proof-perfect-hair-day", product2Id: "kerastase-elixir-ultime",
      winnerId: "kerastase-elixir-ultime",
      winnerReason: "Kérastase Elixir Ultime wins for pure results and luxury experience. Living Proof wins for versatility and value — its 5-in-1 formula replaces more products at a lower price.",
      verdict: "Kérastase Elixir Ultime is the winner for those who want the absolute best hair oil experience. Living Proof 5-in-1 is the smarter purchase for those who want to simplify their routine — it replaces multiple products at a lower total cost.",
      publishDate: TODAY, slug: "living-proof-5in1-vs-kerastase-elixir-ultime",
    },
    {
      id: "t3-featherweight-vs-ghd-helios",
      title: "T3 Featherweight Luxe vs. ghd Helios",
      subtitle: "Lightweight Comfort vs. Maximum Power: Premium Dryer Showdown",
      category: "Hair Dryers", categorySlug: "hair-dryers",
      product1Id: "t3-featherweight-luxe", product2Id: "ghd-helios-hair-dryer",
      winnerId: "ghd-helios-hair-dryer",
      winnerReason: "ghd Helios wins for its superior 2400W power and optimum temperature technology. T3 Featherweight wins for comfort and ease of use during extended styling sessions.",
      verdict: "ghd Helios is the better dryer in absolute terms — more powerful, faster, and with better heat control technology. T3 Featherweight Luxe is the better choice for those who prioritize comfort during extended use or have fine hair that doesn't need maximum power.",
      publishDate: TODAY, slug: "t3-featherweight-vs-ghd-helios",
    },
    {
      id: "chi-air-vs-verb-ghost-flat-iron",
      title: "CHI Air Expert vs. Verb Ghost Flat Iron",
      subtitle: "Professional Power vs. Clean Beauty: Which Flat Iron Is Right for You?",
      category: "Flat Irons & Straighteners", categorySlug: "flat-irons",
      product1Id: "chi-air-expert-flat-iron", product2Id: "verb-ghost-flat-iron",
      winnerId: "verb-ghost-flat-iron",
      winnerReason: "Verb Ghost wins for fine and color-treated hair due to its lower temperature range that minimizes damage. CHI Air Expert wins for thick, coarse hair that needs higher heat.",
      verdict: "The winner depends on your hair type. Verb Ghost is the better choice for fine, color-treated, or heat-sensitive hair — the lower temperature range delivers results with significantly less damage. CHI Air Expert is the better choice for thick, coarse hair that needs higher heat to achieve smooth results.",
      publishDate: TODAY, slug: "chi-air-expert-vs-verb-ghost-flat-iron",
    },
    {
      id: "beachwaver-vs-remington-spiral",
      title: "Beachwaver S1 vs. Remington Pro Spiral Wand",
      subtitle: "Self-Rotating Innovation vs. Budget Value: Curling Tool Comparison",
      category: "Curling Irons & Wands", categorySlug: "curling-irons",
      product1Id: "beachwaver-s1-curling-iron", product2Id: "remington-pro-spiral-curler",
      winnerId: "beachwaver-s1-curling-iron",
      winnerReason: "Beachwaver wins for ease of use and versatility — the self-rotating mechanism creates beautiful waves that are difficult to achieve with traditional wands. Remington wins for tight, defined curls at a fraction of the price.",
      verdict: "Beachwaver S1 is the winner for most users — the self-rotating mechanism eliminates the technique barrier and creates beautiful, consistent waves. Remington Pro Spiral is the better choice for those who specifically want tight, defined curls and are comfortable with traditional wand technique.",
      publishDate: TODAY, slug: "beachwaver-s1-vs-remington-pro-spiral",
    },
  ],

  // ── WEEK 2 ──────────────────────────────────────────────
  [
    {
      id: "joico-vs-matrix-biolage-shampoo",
      title: "Joico Color Balance Purple vs. Matrix Biolage HydraSource",
      subtitle: "Toning vs. Hydrating: Choosing the Right Shampoo for Your Needs",
      category: "Shampoo & Conditioner", categorySlug: "shampoo-conditioner",
      product1Id: "joico-color-balance-shampoo", product2Id: "matrix-biolage-hydrasource",
      winnerId: "joico-color-balance-shampoo",
      winnerReason: "Joico Color Balance wins for blonde and gray hair that needs toning — it's the most effective purple shampoo at this price point. Matrix Biolage wins for those who need hydration rather than toning.",
      verdict: "These shampoos serve different purposes. Joico Color Balance is the winner for blonde, highlighted, or gray hair that needs brassiness control. Matrix Biolage HydraSource is the better choice for those whose primary concern is hydration rather than color maintenance.",
      publishDate: TODAY, slug: "joico-color-balance-vs-matrix-biolage-hydrasource",
    },
    {
      id: "philip-kingsley-vs-christophe-robin",
      title: "Philip Kingsley Elasticizer vs. Christophe Robin Regenerating Mask",
      subtitle: "Pre-Shampoo Treatment vs. Luxury Mask: Which Repairs Better?",
      category: "Hair Masks & Treatments", categorySlug: "hair-masks",
      product1Id: "philip-kingsley-elasticizer", product2Id: "christophe-robin-mask",
      winnerId: "christophe-robin-mask",
      winnerReason: "Christophe Robin wins for severely damaged hair due to its rare prickly pear oil that delivers more intensive regeneration. Philip Kingsley wins for fine hair that needs elasticity restoration without heaviness.",
      verdict: "Christophe Robin Regenerating Mask is the winner for severely damaged or bleached hair — the prickly pear oil delivers more intensive repair. Philip Kingsley Elasticizer is the better choice for fine hair that has lost elasticity but isn't severely damaged.",
      publishDate: TODAY, slug: "philip-kingsley-elasticizer-vs-christophe-robin-mask",
    },
    {
      id: "bumble-vs-verb-ghost-oil",
      title: "Bumble and bumble Invisible Oil vs. Verb Ghost Oil",
      subtitle: "Luxury Weightless Oil vs. Clean Beauty Value: Which Is Better?",
      category: "Serums & Oils", categorySlug: "serums-oils",
      product1Id: "bumble-hairdressers-invisible-oil", product2Id: "verb-ghost-oil",
      winnerId: "verb-ghost-oil",
      winnerReason: "Verb Ghost Oil wins for value and clean formula — it delivers comparable weightless results to Bumble at half the price, with a cleaner ingredient list. Bumble wins for the prestige experience and heat protection.",
      verdict: "Verb Ghost Oil is the smarter purchase for most users — it delivers comparable lightweight shine results to Bumble and bumble at half the price, with a cleaner formula. Bumble and bumble Invisible Oil is worth the premium for those who prioritize the prestige experience or need the higher heat protection (450°F vs. 400°F).",
      publishDate: TODAY, slug: "bumble-invisible-oil-vs-verb-ghost-oil",
    },
    {
      id: "parlux-vs-dyson-airwrap",
      title: "Parlux 385 vs. Dyson Airwrap Complete",
      subtitle: "Professional Workhorse vs. Multi-Styler: Which Is Worth the Investment?",
      category: "Hair Dryers", categorySlug: "hair-dryers",
      product1Id: "parlux-385-powerlight", product2Id: "dyson-airwrap-complete",
      winnerId: "dyson-airwrap-complete",
      winnerReason: "Dyson Airwrap wins for versatility — it replaces multiple styling tools. Parlux wins for pure drying power, durability, and value as a dedicated dryer.",
      verdict: "The winner depends on your needs. Dyson Airwrap is the better choice if you want one tool that dries, curls, and smooths. Parlux 385 is the better choice if you specifically need a powerful, durable dryer for daily use — it's a third of the price and built to last years of professional use.",
      publishDate: TODAY, slug: "parlux-385-vs-dyson-airwrap-complete",
    },
    {
      id: "babyliss-pro-vs-remington-pearl",
      title: "BaBylissPRO Ultra-Thin vs. Remington Pearl Pro",
      subtitle: "Professional Precision vs. Mid-Range Value: Flat Iron Comparison",
      category: "Flat Irons & Straighteners", categorySlug: "flat-irons",
      product1Id: "babyliss-pro-nano-titanium-flat", product2Id: "remington-s9500-pearl-pro",
      winnerId: "babyliss-pro-nano-titanium-flat",
      winnerReason: "BaBylissPRO wins for precision styling capability and professional-grade durability. Remington Pearl Pro wins for value — it delivers excellent results at $10 less.",
      verdict: "BaBylissPRO Ultra-Thin is the winner for those who need precision styling or professional durability. Remington Pearl Pro is the better value for everyday straightening — it delivers excellent results at a lower price, though it won't match the precision or longevity of the BaBylissPRO.",
      publishDate: TODAY, slug: "babyliss-pro-ultra-thin-vs-remington-pearl-pro",
    },
    {
      id: "hot-tools-vs-sultra-bombshell",
      title: "Hot Tools One-Shot vs. Sultra The Bombshell",
      subtitle: "Classic Clip Iron vs. Premium Clipless Rod: Which Creates Better Curls?",
      category: "Curling Irons & Wands", categorySlug: "curling-irons",
      product1Id: "hot-tools-one-shot-curling-iron", product2Id: "sultra-bombshell-curling-rod",
      winnerId: "sultra-bombshell-curling-rod",
      winnerReason: "Sultra Bombshell wins for natural-looking results and eliminating clip marks. Hot Tools wins for ease of use and value — the clip design is more beginner-friendly at a lower price.",
      verdict: "Sultra Bombshell is the winner for those who want the most natural-looking curls without clip marks. Hot Tools One-Shot is the better choice for beginners or those who prefer the ease and control of a clip-style iron at a much lower price.",
      publishDate: TODAY, slug: "hot-tools-one-shot-vs-sultra-bombshell",
    },
  ],

  // ── WEEK 3 ──────────────────────────────────────────────
  [
    {
      id: "aveda-vs-oribe-shampoo",
      title: "Aveda Nutriplenish vs. Oribe Gold Lust Shampoo",
      subtitle: "Clean Beauty vs. Ultra-Luxury: Is Oribe Worth 50% More?",
      category: "Shampoo & Conditioner", categorySlug: "shampoo-conditioner",
      product1Id: "aveda-nutriplenish-shampoo", product2Id: "oribe-gold-lust-shampoo",
      winnerId: "oribe-gold-lust-shampoo",
      winnerReason: "Oribe Gold Lust wins for results, scent, and the overall luxury experience. Aveda wins for clean beauty credentials and those who prioritize plant-based formulas.",
      verdict: "Oribe Gold Lust is the winner for those who want the absolute best shampoo experience — the biotin complex, Côte d'Azur scent, and overall luxury are unmatched. Aveda Nutriplenish is the better choice for clean beauty enthusiasts who prioritize plant-based formulas and don't want to pay Oribe prices.",
      publishDate: TODAY, slug: "aveda-nutriplenish-vs-oribe-gold-lust",
    },
    {
      id: "fanola-vs-kerastase-resistance",
      title: "Fanola No Yellow Mask vs. Kérastase Résistance Masque",
      subtitle: "Toning Treatment vs. Repair Mask: Different Goals, Different Winners",
      category: "Hair Masks & Treatments", categorySlug: "hair-masks",
      product1Id: "fanola-no-yellow-mask", product2Id: "kerastase-resistance-masque",
      winnerId: "kerastase-resistance-masque",
      winnerReason: "Kérastase Résistance wins for structural repair of damaged hair. Fanola wins for toning and brassiness correction in blonde hair.",
      verdict: "These masks serve fundamentally different purposes. Fanola No Yellow is the winner for blonde or gray hair that needs brassiness correction — nothing neutralizes yellow tones more effectively at this price. Kérastase Résistance is the winner for damaged hair that needs structural repair — the ceramide complex rebuilds hair from within.",
      publishDate: TODAY, slug: "fanola-no-yellow-vs-kerastase-resistance-masque",
    },
    {
      id: "amika-serum-vs-olaplex-no3",
      title: "Amika Nourish & Shine vs. Olaplex No. 3",
      subtitle: "Shine Serum vs. Bond Builder: Which Does Your Hair Actually Need?",
      category: "Serums & Oils", categorySlug: "serums-oils",
      product1Id: "amika-nourish-and-shine-serum", product2Id: "olaplex-no3-hair-perfector",
      winnerId: "olaplex-no3-hair-perfector",
      winnerReason: "Olaplex No. 3 wins for damaged hair due to its unique bond-building technology that addresses the root cause of damage. Amika wins for healthy hair that just needs shine and frizz control.",
      verdict: "Olaplex No. 3 is the winner for damaged, chemically processed, or breakage-prone hair — its bond-building technology addresses damage at the molecular level. Amika Nourish & Shine is the better choice for healthy hair that simply needs shine and frizz control without the intensive repair.",
      publishDate: TODAY, slug: "amika-nourish-shine-vs-olaplex-no3",
    },
    {
      id: "bio-ionic-vs-conair-spin-air",
      title: "Bio Ionic GoldPro vs. Conair Infiniti PRO Spin Air",
      subtitle: "Premium Speed vs. Budget Versatility: Hair Dryer Comparison",
      category: "Hair Dryers", categorySlug: "hair-dryers",
      product1Id: "bio-ionic-goldpro-dryer", product2Id: "conair-infiniti-pro-spin-air",
      winnerId: "bio-ionic-goldpro-dryer",
      winnerReason: "Bio Ionic GoldPro wins for pure drying speed and shine results. Conair Spin Air wins for versatility and value — the rotating barrel creates blowout results that the Bio Ionic can't match.",
      verdict: "Bio Ionic GoldPro is the winner for those who want the fastest, shiniest blowdry results. Conair Spin Air is the better choice for those who want a tool that both dries and styles simultaneously — the rotating barrel creates voluminous blowouts that justify its lower price.",
      publishDate: TODAY, slug: "bio-ionic-goldpro-vs-conair-spin-air",
    },
    {
      id: "remington-pearl-vs-t3-whirl",
      title: "Remington Pearl Pro vs. T3 Whirl Trio",
      subtitle: "Budget Single vs. Premium Multi-Barrel: Is the T3 Worth 5x the Price?",
      category: "Flat Irons & Straighteners", categorySlug: "flat-irons",
      product1Id: "remington-s9500-pearl-pro", product2Id: "t3-whirl-trio-curling-iron",
      winnerId: "t3-whirl-trio-curling-iron",
      winnerReason: "T3 Whirl Trio wins for versatility — three interchangeable barrels replace multiple tools. Remington wins for value as a dedicated straightener.",
      verdict: "T3 Whirl Trio is the winner for those who regularly use multiple curl sizes — it replaces three separate tools at a lower total cost. Remington Pearl Pro is the better choice for those who only need a flat iron and don't require curling capability.",
      publishDate: TODAY, slug: "remington-pearl-pro-vs-t3-whirl-trio",
    },
    {
      id: "kristin-ess-vs-hot-tools-24k",
      title: "Kristin Ess Curling Wand vs. Hot Tools 24K Gold",
      subtitle: "Influencer Brand vs. Professional Classic: Which Creates Better Curls?",
      category: "Curling Irons & Wands", categorySlug: "curling-irons",
      product1Id: "kristin-ess-curling-wand", product2Id: "hot-tools-24k-gold-curling-iron",
      winnerId: "hot-tools-24k-gold-curling-iron",
      winnerReason: "Hot Tools 24K Gold wins for professional-grade results and durability. Kristin Ess wins for value and the titanium barrel's consistent heat.",
      verdict: "Hot Tools 24K Gold is the winner for professional results and long-term durability — the gold barrel technology delivers consistent, polished curls that last. Kristin Ess is the better value for those who want titanium performance at a lower price and don't need the extra durability of a professional tool.",
      publishDate: TODAY, slug: "kristin-ess-vs-hot-tools-24k-gold",
    },
  ],
];

// ============================================================
// MAIN UPDATE LOGIC
// ============================================================
function addWeeklyContent() {
  const weekIndex = (WEEK_NUMBER - 1) % weeklyProducts.length;
  const productsToAdd = weeklyProducts[weekIndex] || [];
  const comparisonsToAdd = weeklyComparisons[weekIndex] || [];

  console.log(`\n📅 Week ${WEEK_NUMBER} update (queue index ${weekIndex})`);
  console.log(`   Adding ${productsToAdd.length} products and ${comparisonsToAdd.length} comparisons`);

  let content = readFileSync(PRODUCTS_FILE, "utf-8");

  // Add new products
  for (const product of productsToAdd) {
    if (content.includes(`id: "${product.id}"`)) {
      console.log(`   ⏭️  Product "${product.id}" already exists, skipping`);
      continue;
    }

    const hairTypesStr = JSON.stringify(product.hairTypes || []);
    const prosStr = JSON.stringify(product.pros);
    const consStr = JSON.stringify(product.cons);
    const fullReviewEscaped = product.fullReview.replace(/`/g, "\\`").replace(/\${/g, "\\${");

    const productEntry = `
  {
    id: "${product.id}",
    name: "${product.name.replace(/"/g, '\\"')}",
    brand: "${product.brand}",
    asin: "${product.asin}",
    price: ${product.price},
    priceDisplay: "${product.priceDisplay}",
    rating: ${product.rating},
    reviewCount: ${product.reviewCount},
    category: "${product.category}",
    categorySlug: "${product.categorySlug}",
    imageUrl: "${product.imageUrl}",
    amazonImageUrl: "${product.amazonImageUrl}",
    hairTypes: ${hairTypesStr},
    shortDescription: "${product.shortDescription.replace(/"/g, '\\"')}",
    fullReview: \`${fullReviewEscaped}\`,
    pros: ${prosStr},
    cons: ${consStr},
    bestFor: "${product.bestFor.replace(/"/g, '\\"')}",
    editorPick: ${product.editorPick || false},
    publishDate: "${product.publishDate}",
    slug: "${product.slug}",
  },`;

    content = content.replace(
      "export const allProducts: Product[] = [",
      `export const allProducts: Product[] = [${productEntry}`
    );
    console.log(`   ✅ Added product: ${product.name}`);
  }

  // Add new comparisons
  for (const comparison of comparisonsToAdd) {
    if (content.includes(`id: "${comparison.id}"`)) {
      console.log(`   ⏭️  Comparison "${comparison.id}" already exists, skipping`);
      continue;
    }

    const comparisonEntry = `
  {
    id: "${comparison.id}",
    title: "${comparison.title.replace(/"/g, '\\"')}",
    subtitle: "${comparison.subtitle.replace(/"/g, '\\"')}",
    category: "${comparison.category}",
    categorySlug: "${comparison.categorySlug}",
    product1Id: "${comparison.product1Id}",
    product2Id: "${comparison.product2Id}",
    winnerId: "${comparison.winnerId}",
    winnerReason: "${comparison.winnerReason.replace(/"/g, '\\"')}",
    verdict: "${comparison.verdict.replace(/"/g, '\\"')}",
    publishDate: "${comparison.publishDate}",
    slug: "${comparison.slug}",
  },`;

    content = content.replace(
      "export const comparisons: Comparison[] = [",
      `export const comparisons: Comparison[] = [${comparisonEntry}`
    );
    console.log(`   ✅ Added comparison: ${comparison.title}`);
  }

  writeFileSync(PRODUCTS_FILE, content, "utf-8");
  console.log(`\n✅ Week ${WEEK_NUMBER} update complete — ${productsToAdd.length} products, ${comparisonsToAdd.length} comparisons added\n`);
}

addWeeklyContent();
